name: Deployment

on:
  workflow_dispatch:
    inputs:
      web:
        type: boolean
        description: web
      api:
        type: boolean
        description: api
      mediasoup:
        type: boolean
        description: mediasoup
      recording:
        type: boolean
        description: recording

      migrate:
        type: boolean
        description: run migration
      seed:
        type: boolean
        description: run seed
