name: Deployment

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Deployment mode
        required: true
        default: 'all'
        options:
          - all (web,api,mediasoup,recording)
          - minimal (web,api)
          - backend (api,mediasoup,recording)
          - backend-media (api,mediasoup)
          - backend-recording (api,recording)
          - frontend only (web only)
          - api only
          - mediasoup only
          - recording only

      migrate:
        type: boolean
        description: run migration

jobs:
  deploy:
    name: deployment
    runs-on: ubuntu-latest
    steps:
    - name: logging
      run: echo "Deploying ${{ github.event.inputs.mode }} mode ${{ github.event.inputs.migrate?'with migration':'' }}"
