name: Deployment

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: choose deployment mode
        options:
          - all - deploy web, api, mediasoup, recording
          - web only
          - api only
          - mediasoup only
          - recording only
        
      web:
        type: boolean
        description: web
      api:
        type: boolean
        description: api
      mediasoup:
        type: boolean
        description: mediasoup
      recording:
        type: boolean
        description: recording

      migrate:
        type: boolean
        description: run migration
      seed:
        type: boolean
        description: run seed

jobs:
  deploy:
    name: deployment
    runs-on: ubuntu-latest
    steps:
    - name: logging
      run: echo "Deploying ${{ github.event.inputs.mode }} mode"
